### ISSUE TITLE
Chart dynamic values not updated.

### ISSUE THREAD

**Issue by sakthivelsubbarayan** [amanjain325/angular-d3-charts#2]
I try to update the chart values in dynamically.But it not updated.

**Comment by Dhansekaran** [comment]
I have the same problem. when i change the data chat not updating. can some one provide the solution for this problem.

**Comment by amanjain325** [comment]
Right now, it can be resolved by css only. I will add this functionality by code.

**Comment by tjdiya** [comment]
I have the same problem, i am trying to update the date in onInit but not working
