### ISSUE TITLE
Production Build Not Working : ng build --prod

### ISSUE THREAD

**Issue by atulgupt** [amanjain325/angular-d3-charts#4]
Hello There!

I was using this library for drawing the DoNut Chart. 
When I am going to make the production build. I am getting the 

**ERROR in : Unexpected value 'DoughnutChartComponent in /Users/kiwitech/quardant-vms-frontend/node_modules/angular-d3-charts/bundle/doughnutChart.component.d.ts' declared by the module 'DashboardQuadrantModule in /Users/kiwitech/quardant-vms-frontend/src/app/quadrant/dashboard/dashboard.module.ts'. Please add a @Pipe/@Directive/@Component annotation.**

I hope this issue will be resolved in the future.

Thanks,

**Comment by rishi-mobi** [comment]
> Hello There!
> 
> I was using this library for drawing the DoNut Chart.
> When I am going to make the production build. I am getting the
> 
> **ERROR in : Unexpected value 'DoughnutChartComponent in /Users/kiwitech/quardant-vms-frontend/node_modules/angular-d3-charts/bundle/doughnutChart.component.d.ts' declared by the module 'DashboardQuadrantModule in /Users/kiwitech/quardant-vms-frontend/src/app/quadrant/dashboard/dashboard.module.ts'. Please add a @Pipe/@Directive/@component annotation.**
> 
> I hope this issue will be resolved in the future.
> 
> Thanks,

How did you solve this issue ?

**Comment by atulgupt** [comment]
> > Hello There!
> > I was using this library for drawing the DoNut Chart.
> > When I am going to make the production build. I am getting the
> > **ERROR in : Unexpected value 'DoughnutChartComponent in /Users/kiwitech/quardant-vms-frontend/node_modules/angular-d3-charts/bundle/doughnutChart.component.d.ts' declared by the module 'DashboardQuadrantModule in /Users/kiwitech/quardant-vms-frontend/src/app/quadrant/dashboard/dashboard.module.ts'. Please add a @Pipe/@Directive/@component annotation.**
> > I hope this issue will be resolved in the future.
> > Thanks,
> 
> How did you solve this issue ?

**Comment by atulgupt** [comment]
> > Hello There!
> > I was using this library for drawing the DoNut Chart.
> > When I am going to make the production build. I am getting the
> > **ERROR in : Unexpected value 'DoughnutChartComponent in /Users/kiwitech/quardant-vms-frontend/node_modules/angular-d3-charts/bundle/doughnutChart.component.d.ts' declared by the module 'DashboardQuadrantModule in /Users/kiwitech/quardant-vms-frontend/src/app/quadrant/dashboard/dashboard.module.ts'. Please add a @Pipe/@Directive/@component annotation.**
> > I hope this issue will be resolved in the future.
> > Thanks,
> 
> How did you solve this issue ?

I wasn't able to resolve it, So I switched to another library **ng-circle-progress** 

[https://www.npmjs.com/package/ng-circle-progress](url)

Thanks,
